# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    authentication.handler.login_success_handler:
        class:  AppBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
    app_user.password_change:
            class: AppBundle\EventListener\ChangePasswordListener
            arguments: ['@router', '@security.authorization_checker']
            tags:
                - { name: kernel.event_subscriber }
    app_user.penalty_warning:
            class: AppBundle\Services\PenaltyWarning
            arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']